# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
