# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_link_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='title',
            field=models.CharField(default='Link', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='backend.Topic'),
        ),
    ]
