# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 01:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20160226_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 8, 1, 21, 42, 301291, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
