# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20160408_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='name',
            field=models.CharField(default='Variables', max_length=100),
            preserve_default=False,
        ),
    ]
