# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 14:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0006_level_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VocabWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('term', models.CharField(max_length=1000)),
                ('definition', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocab_word', to='backend.Topic')),
            ],
        ),
        migrations.AlterField(
            model_name='level',
            name='topics',
            field=models.ManyToManyField(blank=True, to='backend.Topic'),
        ),
        migrations.AlterField(
            model_name='level',
            name='trajectory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='backend.Trajectory'),
        ),
        migrations.AlterField(
            model_name='link',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='backend.Topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='comments',
            field=models.ManyToManyField(blank=True, to='backend.Comment'),
        ),
    ]
